"""Rebuild frontend/css/style.css from parts/*.css.

Why not @import? @import inside a linked stylesheet forces a
sequential network waterfall — every partial blocks first paint
behind the previous one's parse. On slow mobile connections this
adds ~500-1500ms to the time-to-first-paint.

Instead we keep the partials as a developer navigation aid and
ship one concatenated bundle. Edit a partial, then run::

    uv run python scripts/rebuild_css.py

The bundle is checked in so the live site doesn't depend on the
build step at deploy time.
"""

from __future__ import annotations

from pathlib import Path

import rcssmin

ROOT = Path(__file__).resolve().parent.parent / "frontend" / "css"
PARTS_ORDER = ("tokens", "layout", "modals", "pipeline", "states", "ai", "brand")

# OPUS-13: header is intentionally short — rcssmin keeps the first
# block-comment in the file (so the "this file is generated"
# marker survives), but each extra byte ships to every visitor.
_HEADER = (
    "/*! style.css — generated by scripts/rebuild_css.py. "
    "Edit ./parts/*.css and rerun the script. */\n"
)


def _concat_css() -> str:
    """Pre-minification concatenation of partials.

    Each partial gets a brief separator comment so a developer
    grepping the unminified intermediate can still navigate by
    section name. The minifier strips ordinary comments, leaving
    only the bang-comment header above.
    """
    chunks: list[str] = [_HEADER]
    for name in PARTS_ORDER:
        partial = ROOT / "parts" / f"{name}.css"
        if not partial.exists():
            raise SystemExit(f"missing partial: {partial}")
        body = partial.read_text(encoding="utf-8")
        chunks.append(f"/* ===== {name} ===== */\n")
        chunks.append(body)
        if not body.endswith("\n"):
            chunks.append("\n")
        chunks.append("\n")
    return "".join(chunks)


def build_css_text() -> str:
    """Concatenated + minified CSS.

    OPUS-13: ``rcssmin`` strips whitespace and ordinary comments
    while preserving ``/*! ... */`` bang-comments and selector
    semantics. No declaration mangling, no shorthand collapsing —
    same trade-off as ``rjsmin`` for JS.
    """
    return rcssmin.cssmin(_concat_css())


def rebuild() -> None:
    css = build_css_text()
    (ROOT / "style.css").write_text(css, encoding="utf-8")
    print(f"style.css: {len(css)} bytes from {len(PARTS_ORDER)} partials")


if __name__ == "__main__":
    rebuild()
